### ISSUE TITLE
Buy a decent icon set for actions

### ISSUE THREAD

**Issue by phae** [codeforamerica/ceviche-cms#103]
Borrowed a few from the noun project for now, but once we're settled on them, buy them/attribute appropriately.

**Comment by migurski** [comment]
These two sets are reasonable and MIT-licensed:

* http://raphaeljs.com/icons/ (okay)
* http://ionicons.com (better)

**Comment by phae** [comment]
I like the ion ones. I'll switch those in.

**Comment by phae** [comment]
IonIcons are now available. We're only using 5 of them right now, so I'm just using them directly rather than sending down the whole set as a font. If we suddenly start using a lot, then we should probably switch to that.
