### ISSUE TITLE
Replace environment with config

### ISSUE THREAD

**Issue by migurski** [codeforamerica/ceviche-cms#108]
Need to stop using environment deep down.

**Comment by migurski** [comment]
@tmaybe, I’m working in [replace-environ-with-config-#108](https://github.com/codeforamerica/ceviche-cms/tree/replace-environ-with-config-%23108). I’ve left a couple un-done in `google_api_functions.py`.

**Comment by tmaybe** [comment]
I accept your assignation. I was worried about integrating this with my work on #96 anyway.
