### ISSUE TITLE
Make a POST required to create new branches

### ISSUE THREAD

**Issue by migurski** [codeforamerica/ceviche-cms#147]
Right now it looks like new branches are created based on GET + URL.

**Comment by tmaybe** [comment]
@migurski a POST is used to create a new branch when you push the _Create Task_ button, see [the HTML](https://github.com/codeforamerica/ceviche-cms/blob/master/bizarro/templates/index.html#L39-L42) and [the code](https://github.com/codeforamerica/ceviche-cms/blob/master/bizarro/views.py#L176-L187). Where do you see a GET used to create a new branch?

**Comment by migurski** [comment]
Frances and I were both finding that new branches were being created implicitly when requested with a GET, like if you just typed something into the location.
