### ISSUE TITLE
Add an audit log for any page

### ISSUE THREAD

**Issue by phae** [codeforamerica/ceviche-cms#19]
There's a placement link on the edit content page marked "History". Should show who/when/what was edited about that page.

An old dummy template for that is here: https://github.com/codeforamerica/bizarro-cms/blob/master/prototype/history.html

**Comment by migurski** [comment]
Old dummy template is actually here: http://jekit.codeforamerica.org/codeforamerica/ceviche-cms/ba9b2d708/prototype/history.html

**Comment by migurski** [comment]
Check out work in progress on branch `add-page-audit-log-#19`.

**Comment by phae** [comment]
Kickin' it back to you, @migurski. See sketchy for {{path}} - if you can make that go, we can call this one a day and move over to #49 for the rest!
