### ISSUE TITLE
Ability to setup a new instance (setup app style? point to an existing content repo?)

### ISSUE THREAD

**Issue by phae** [codeforamerica/ceviche-cms#39]

**Comment by phae** [comment]
For the default templates, point to ceviche-starter repo

**Comment by migurski** [comment]
Spent some quality time with this need today, I think we have a path forward.

We will need to create a new Ceviche setup script, and it will:

1. Do the OAuth dance with Github to get a token [with `repo` scope](https://developer.github.com/v3/oauth/#scopes).
2. Create a new Ceviche instance on EC2, with the token in the EC2 user data.
  1. Ceviche instance will use the token to create [a new Github repository](https://developer.github.com/v3/repos/#create) and [deploy key](https://developer.github.com/v3/repos/keys/#create).
  2. Ceviche instance will clone the [starter repo](https://github.com/codeforamerica/ceviche-starter), and push it to the newly-created repo.
3. Setup script will watch for the new repository to be created.
4. Setup script will [delete the auth token](https://developer.github.com/v3/oauth_authorizations/#delete-an-authorization) on completion.

**Comment by migurski** [comment]
In-progress: 

* [setup-script.py](https://github.com/codeforamerica/ceviche-cms/blob/fa6019d7fd598236e58a8b25e51050e4bc71c921/setup-script.py) for authenticating with Github and starting instance,
* [chef/bizarro/recipes/default.rb](https://github.com/codeforamerica/ceviche-cms/blob/fa6019d7fd598236e58a8b25e51050e4bc71c921/chef/bizarro/recipes/default.rb) for creating Github repository and deploy keys.
