### ISSUE TITLE
NAME IT

### ISSUE THREAD

**Issue by phae** [codeforamerica/ceviche-cms#42]
What's it's grown-up name?

**Comment by phae** [comment]
migurski: Innobasics™

**Comment by phae** [comment]
Mirguski: thebasics
Cyd: DialTone

**Comment by phae** [comment]
cc @danhon @Jaime-Alexis

**Comment by Jaime-Alexis** [comment]
GovBuilder
Civic Builder
Civic CMS

**Comment by phae** [comment]
I really, really don't want the word "civic" in it. I feel like that's a super saturated word.

I also feel like it would be good for the overall DFD branding if it felt like it was related to, or rather, inside of the overall DFD practice.

**Comment by meghanreilly** [comment]
Civic Platform


On Fri, Feb 13, 2015 at 10:49 AM, Jaime-Alexis <notifications@github.com>
wrote:

> GovBuilder
> Civic Builder
> Civic CMS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/ceviche-cms/issues/42#issuecomment-74305006>
> .
>



-- 
*Help local governments deliver better services to communities. Donate now.
<https://secure.codeforamerica.org/page/contribute/default?source_codes=staff>*

Meghan Reilly
CFO & CAO, Code for America
c: 415-226-8975
@mfreilly

**Comment by meghanreilly** [comment]
City Platform
City Platform Services

Clearly I like Platform ;)

On Fri, Feb 13, 2015 at 10:50 AM, Frances Berriman <notifications@github.com
> wrote:

> I really, really don't want the word "civic" in it. I feel like that's a
> super saturated word.
>
> I also feel like it would be good for the overall DFD branding if it felt
> like it was related to, or rather, inside of the overall DFD practice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/ceviche-cms/issues/42#issuecomment-74305184>
> .
>



-- 
*Help local governments deliver better services to communities. Donate now.
<https://secure.codeforamerica.org/page/contribute/default?source_codes=staff>*

Meghan Reilly
CFO & CAO, Code for America
c: 415-226-8975
@mfreilly

**Comment by Ldskywalker79** [comment]
If we're only talking about the Content Management System, I would consider
GovCMS, GovContent+, GovWeb

I love the idea of Civic Web Stack -- as it's clear and people get it. DFD
for folks I think takes some time to understand, but it's already out
there. But, I also hear what Frances is saying.

On Fri, Feb 13, 2015 at 12:49 PM, Jaime-Alexis <notifications@github.com>
wrote:

> GovBuilder
> Civic Builder
> Civic CMS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/ceviche-cms/issues/42#issuecomment-74305006>
> .
>



-- 
Luke D. Norris | Director, Government Relations | Code for America
<http://codeforamerica.org/> | c: 816-200-8925 | @norrisluke

**Comment by Jaime-Alexis** [comment]
@phae understood. What would help signal that it's for municipal govs? Or help is show up if someone is searching an oversaturated word like 'civic'?

**Comment by mattboitan0** [comment]
Tributary
OneVoice
Public People Power

**Comment by phae** [comment]
@Jaime-Alexis the language within the DFD project signals that it's for municipal govs. It could also easily come from a snappy tagline that goes beneath. Just for example (this, but not this, but like this): "thebasics: a simple CMS for municipal governments", you know?

**Comment by Jaime-Alexis** [comment]
![image](https://cloud.githubusercontent.com/assets/7927857/6193337/2748f956-b36f-11e4-9efe-713a63b5aac2.png)
Quick search on Google Trends

**Comment by Jaime-Alexis** [comment]
@phae for sure. Only flag..."simple" and "basic" may signal 'it's not important enough or robust enough to do what we want...'? Something we could test though and get some perceptions around.

**Comment by phae** [comment]
Yes, that was an example. They may be the wrong words, I just meant that we want to have a fun, unique name that ties it to DFD and rely on a good, snappy, slogan/tagline to satisfy the understanding and search-ability, such as these real examples:

Perch: A really little content management system
Slack: A platform for team communication: everything in one place, instantly searchable, available wherever you go.
Wordpress: The best place for your personal blog or business site.

etc. etc.

**Comment by tmaybe** [comment]
They named HAL by letter shifting IBM – we could letter shift CMS and get BLR (Blur?) or DNT (Dent?)

**Comment by phae** [comment]
Migurki: Lintel (as in, supporting structures around [digital] front doors)

**Comment by phae** [comment]
Chime (as in a digital front doorbell)

**Comment by lippytak** [comment]
I really like Chime. I want it now. How much??

**Comment by Jaime-Alexis** [comment]
+1 on Chime.

**Comment by migurski** [comment]
Comes with a theme song! https://www.youtube.com/watch?v=dDdq5_ZzBRw

**Comment by lanebecker** [comment]
agreed! chime is great.

**Comment by danhon** [comment]
+1 on Chime

**Comment by phae** [comment]
:dancers:

**Comment by Jaime-Alexis** [comment]
Btw, if we want, we could do some market testing a bit with a few names...just a thought.

**Comment by phae** [comment]
The next port of call for this ticket is a conversation with Dan and Debs.
We may well have something to test after that - most specifically
short-copy snippet - I'll open new tickets as appropriate and ask for help
on those. To stop the sprawl, I think we'll consider this closed for now
unless we hit a problem with it. Thank you everyone. :)
