### ISSUE TITLE
Google Analytics configuration

### ISSUE THREAD

**Issue by phae** [codeforamerica/ceviche-cms#47]
There's a basic flow for this now, but it needs some work and a more user-friendly setup.

**Comment by migurski** [comment]
Done in #105. Does this ticket become a language/UI pass on @tmaybe’s code work?

**Comment by phae** [comment]
Yeah, that seems like a good idea. @tmaybe: if you can show me around the interface as it stands, I can sprinkle a little bit of something or other.

**Comment by tmaybe** [comment]
@phae any time!

**Comment by phae** [comment]
Done first pass. Will cover this again when I do a microcopy writing session with content team in 2 weeks.
