### ISSUE TITLE
Add / invite new user

### ISSUE THREAD

**Issue by phae** [codeforamerica/ceviche-cms#62]
* [x] Decide where user account list should live (spreadsheet trick?)
* [ ] Auth a persona account against the list
* [ ] Who gets to make invitations, create accounts?

**Comment by migurski** [comment]
(edited the description with some todo’s)

**Comment by migurski** [comment]
Look into webby ways to get mailto talking to Gmail for those so inclined.

**Comment by migurski** [comment]
Current theory is that we’ll generate a new Google spreadsheet for a user, and give them access to be able to modify permissions themselves.

**Comment by migurski** [comment]
@phae I’m kicking this over to you, to put some dummy content into this spreadsheet that I can parse:

https://docs.google.com/a/codeforamerica.org/spreadsheets/d/12jUfaRBd-CU1_6BGeLFG1_qoi7Fw_vRC_SXv36eDzM0/edit#gid=0

**Comment by phae** [comment]
OK, I've formatted it some so that it's hopefully understandable to a human looking at it and editing it, as well as still parseable for you (who is obviously not a human and is a robot).

![bender](https://cloud.githubusercontent.com/assets/44568/6180695/a05f4a3a-b2dd-11e4-8c83-201b69a8f007.gif)

**Comment by migurski** [comment]
Looks great! I made a formatting tweak on a new sheet, putting the two categories side by side.

**Comment by phae** [comment]
Side by side is better!

**Comment by migurski** [comment]
This issue is getting a bit long in the tooth; I'd like to replace it with a more specific one (#122) now that we’ve made a bunch of progress and decisions.

**Comment by phae** [comment]
:+1:
