### ISSUE TITLE
Buy domain name, configure it

### ISSUE THREAD

**Issue by migurski** [codeforamerica/ceviche-cms#73]
We’ll want to set up “nice” subdomains for users.

* [x] Determine if Route 53 offers API access to create new CNAME records.
* [x] Pick a name, buy it
* [x] Host DNS at AWS Route 53
* [ ] Connect to setup script.

**Comment by migurski** [comment]
Lower priority than https://github.com/codeforamerica/ceviche-cms/issues/74

**Comment by migurski** [comment]
Route53 does allow record creation via the API, but DNS propagation can be slow and I don’t think we should use it. Other options include placing instances of CMS on a single host, or proxying instances to multiple hosts.

**Comment by migurski** [comment]
Bought chime-cms.org, chimecms.org, and chime-cms.com. Someone squatted chimecms.com so we’ll be ignoring that for now.

**Comment by phae** [comment]
:bell: :dancers:

**Comment by migurski** [comment]
What looks better as the official domain, chime-cms.org or chimecms.org? The latter matches the Github org name, which we could change if we like the dash.

**Comment by phae** [comment]
The latter (no hyphen).

**Comment by migurski** [comment]
Great. I'll do redirects from the hyphenated version.

**Comment by cydharrell** [comment]
Too late, but luckily in agreement too.

On Thursday, February 26, 2015, migurski <notifications@github.com> wrote:

> Great. I'll do redirects from the hyphenated version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/ceviche-cms/issues/73#issuecomment-76212066>
> .
>


-- 
Cyd Harrell
Product Director
cyd@codeforamerica.org

**Comment by migurski** [comment]
Since my comment above, we’ve identified a need for a central Ceviche service to route Google callbacks and perform other functions, so I think it can also act as a proxy while DNS propagation takes place.
